#!/usr/bin/env python
# -*- coding, utf-8 -*-

rKeywords = [
    (r'anova\(','anova()'),
    (r'aov\(','aov()'),
    (r'apply\(','apply()'),
    (r'as.factor\(','as.factor()'),
    (r'as.table\(','as.table()'),
    (r'as.vector\(','as.vector()'),
    (r'as.matrix\(','as.matrix()'),
    (r'as.numeric\(','as.matrix()'),
    (r'attach\(','attach()'),
    (r'c\(','c()'),
    (r'cbind\(','cbind()'),
    (r'chisq.test\(', 'chisq.test()'),
    (r'colnames\(','colnames()'),
    (r'cor\(','cor()'),
    (r'cor.test\(','cor.test()'),
    (r'data.frame\(','data.frame()'),
    (r'data.entry\(','data.entry()'),
    (r'detach\(','detach()'),
    (r'dim\(','dim()'),
    (r'factor\(','factor()'),
    (r'fisher.test\(','fisher.test()'),
    (r'friedman.test\(', 'friedman.test()'),
    (r'for ','for ()\n{}'),
    (r'glm\(','glm()'),
    (r'heatmap\(','heatmap()'),
    (r'intersect\(', 'intesect()'),
    (r'runif\(','runif ()\n{}'),
    (r'if ','if()\n{}'),
    (r'is.factor\(','is.factor()'),
    (r'is.vector\(','is.vector()'),
    (r'is.matrix\(','is.matrix()'),
    (r'lapply\(','lapply()'),
    (r'length\(', 'length()'),
    (r'library\(','library()'),
    (r'lines\(','lines()'),
    (r'lm\(','lm()'),
    (r'load\(', 'load()'),
    (r'matrix\(','matrix()'),
    (r'max\(','max()'),
    (r'mean\(','mean()'),
    (r'merge\(','merge()'),
    (r'min\(','min()'),
    (r'names\(','names()'),
    (r'nlm\(','nlm()'),
    (r'print\(', 'print()'),
    (r'prop.test\(', 'prop.test()'),
    (r'qnorm\(','qnorm()'),
    (r'r\(','r()'),
    (r'rbeta\(','rbeta()'),
    (r'rbind\(','rbind()'),
    (r'require\(','require()'),
    (r'read.csv\(','read.csv()'),
    (r'read.table\(','read.table()'),
    (r'rep\(','rep()'),
    (r'rnorm\(','rnorm()'),
    (r'rownames\(','rownames()'),   
    (r'sapply\(','sapply()'),
    (r'seq\(','seq()'),
    (r'source\(', 'source()'),
    (r'scale\(', 'scale()'),
    (r'summary\(', 'summary()'),
    (r'survival\(','survival()'),
    (r'table\(','table()'),
    (r'unique\(', 'unique()'),
    (r'union\(', 'union()'),
    (r'while ','while ()\n{}'),
    (r'write\(', 'write()'),
    (r'write\(.table', 'write.table()'),
    (r'<-', '<-')
    ]
